/* Generated by scripts/sync-store-photos.cjs — do not edit by hand */
import type { StoreGalleryImage } from "./store-gallery.types";

export const SYNCED_STORE_IMAGES: StoreGalleryImage[] = [
  { src: "/stores/10.jpeg", caption: { id: "Lokasi 10 — Bandar Laundry Express", en: "Location 10 — Bandar Laundry Express" } },
  { src: "/stores/15.jpeg", caption: { id: "Lokasi 15 — Bandar Laundry Express", en: "Location 15 — Bandar Laundry Express" } },
  { src: "/stores/17.jpeg", caption: { id: "Lokasi 17 — Bandar Laundry Express", en: "Location 17 — Bandar Laundry Express" } },
  { src: "/stores/18.jpeg", caption: { id: "Lokasi 18 — Bandar Laundry Express", en: "Location 18 — Bandar Laundry Express" } },
];
