/**
 * Store gallery image paths (served from /public/store-gallery).
 * Regenerated by: pnpm run sync-store-photos
 * Source folder: Photos of actual stores/
 */
export const STORE_GALLERY_ITEMS = [{ src: "/store-gallery/store-01.jpeg" }] as const;
